### ISSUE TITLE
Ajustes na página de Grupo Familiar

### ISSUE THREAD

**Issue by anamgholandadev** [THE-TRIADE/frontend#2]
- [x] Criar funcionalidade do botão de  "Adicionar dependente" (acrescentar componente com os campos para preencher)
- [x] Acrescentar lista de objetos do tipo dependente no cadastro de grupo familiar
- [x] Fazer contador para o título abaixo 
- [x] Papel no grupo familiar
![image](https://user-images.githubusercontent.com/128847103/236723322-f0bdcfa5-25c9-434b-8d3a-8776c3c397a0.png)
- [x] Acrescentar botão para poder excluir o dependente "extra" cadastrado, ideia:
![image](https://user-images.githubusercontent.com/128847103/236723660-88467bfc-1c3e-4888-8b57-4175e5d6a263.png)

**Comment by fawnbr** [comment]
Novos bugs:

- [ ] Os dependentes só estão digitando um caractere por vez
- [ ] Ajeitar alinhamento do botão de excluir com o titulo de dependente
